# Generated by Django 5.1.7 on 2025-03-20 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.TextField(choices=[(1, 'Morbilidad'), (2, 'Visita de Campo')], default=1, max_length=1)),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diagnostico.diagnostico')),
            ],
        ),
    ]
