# Generated by Django 5.1.7 on 2025-03-22 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_medico', '0001_initial'),
        ('consulta', '0003_conducta_consulta_ps_consulta_centro_medico_and_more'),
        ('diagnostico', '0001_initial'),
        ('doctor', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='centro_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='centro_medico.centromedico'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='diagnostico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='diagnostico.diagnostico'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='paciente.paciente'),
        ),
    ]
