# Generated by Django 5.1.7 on 2025-03-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporte', models.FileField(upload_to='uploads/% Y/% m/% d/')),
            ],
        ),
    ]
