# Generated by Django 5.1.7 on 2025-03-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_centro_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='apellido',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='ci',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='prefijo_ci',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
