# Generated by Django 5.1.7 on 2025-03-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_medico', '0001_initial'),
        ('doctor', '0003_alter_usuariopersonalizado_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='centro_medico',
        ),
        migrations.AddField(
            model_name='doctor',
            name='centro_medico',
            field=models.ManyToManyField(related_name='doctores', to='centro_medico.centromedico'),
        ),
    ]
